body:
  - type: textBlock
    attributes:
      name: description
      description: >
        Please provide your Tenor.com API key from: https://tenor.com/developer/keyregistration
        - Powered By Tenor
  - type: input
    attributes:
      name: api_key
      label: Tenor API key
      defaultValue: ""
  - type: dropdown
    attributes:
      name: max_results
      label: Max results
      defaultValue: 10
      options:
        - 10
        - 15
        - 20
        - 25
        - 30
  - type: dropdown
    attributes:
      name: default_action
      label: Default action
      defaultValue: Copy to Clipboard
      options:
        - Copy to Clipboard
        - Open website